<script lang="ts">
  import type { CmsDocument, CmsKind } from '../../features/cms/types';
  import { cmsKindLabels } from '../../features/cms/types';
  export let documents: CmsDocument[] = [];
  export let onOpen: (document: CmsDocument) => void;
  export let onCreate: (kind: CmsKind) => void;
  export let onAction: (document: CmsDocument, action: 'publish' | 'unpublish' | 'trash' | 'restore') => void;
  export let busyId = '';
  let query = ''; let kind = ''; let status = 'active';
  $: filtered = documents.filter((document) => (status === 'trash' ? document.status === 'trash' : document.status !== 'trash') && (!kind || document.kind === kind) && (!query || `${document.title} ${document.slug} ${document.category} ${document.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
</script>

<section class="panel" aria-labelledby="cms-content-title">
  <div class="heading"><div><p class="eyebrow">内容库</p><h2 id="cms-content-title">写作与发布</h2></div><div class="new-actions">{#each Object.entries(cmsKindLabels) as [value, label]}<button type="button" on:click={() => onCreate(value as CmsKind)}>新建{label}</button>{/each}</div></div>
  <div class="filters"><label>搜索<input bind:value={query} type="search" placeholder="标题、slug、分类或标签" /></label><label>类型<select bind:value={kind}><option value="">全部类型</option>{#each Object.entries(cmsKindLabels) as [value, label]}<option value={value}>{label}</option>{/each}</select></label><label>范围<select bind:value={status}><option value="active">当前内容</option><option value="trash">回收站</option></select></label></div>
  {#if filtered.length === 0}<p class="empty">没有符合条件的内容。</p>{:else}<div class="table-wrap"><table><thead><tr><th>内容</th><th>状态</th><th>更新</th><th><span class="sr-only">操作</span></th></tr></thead><tbody>{#each filtered as document}<tr><td><button class="text-button" type="button" on:click={() => onOpen(document)}>{document.title || '未命名内容'}</button><small>{cmsKindLabels[document.kind]} · /{document.slug || '未设置 slug'} · v{document.version}</small></td><td><span class:published={document.status === 'published'} class="badge">{document.status === 'published' ? '已发布' : document.status === 'trash' ? '已回收' : '草稿'}</span></td><td>{new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(document.updated_at))}</td><td class="row-actions"><button type="button" on:click={() => onOpen(document)}>编辑</button>{#if document.status === 'trash'}<button type="button" disabled={busyId === document.id} on:click={() => onAction(document, 'restore')}>恢复</button>{:else if document.status === 'published'}<button type="button" disabled={busyId === document.id} on:click={() => onAction(document, 'unpublish')}>撤回</button>{:else}<button type="button" disabled={busyId === document.id} on:click={() => onAction(document, 'publish')}>发布</button>{/if}{#if document.status !== 'trash'}<button type="button" class="danger" disabled={busyId === document.id} on:click={() => onAction(document, 'trash')}>回收</button>{/if}</td></tr>{/each}</tbody></table></div>{/if}
</section>

<style>
  .panel { padding: clamp(1rem, 3vw, 1.5rem); border: 1px solid var(--site-border); border-radius: .7rem; background: var(--site-surface); } .heading { display:flex; flex-wrap:wrap; justify-content:space-between; gap:1rem; align-items:start; } .eyebrow { margin:0; color:var(--site-link); font-weight:750; font-size:.8rem; } h2 { margin:.15rem 0 0; font-size:1.45rem; } .new-actions,.row-actions { display:flex; flex-wrap:wrap; gap:.4rem; } button, input, select { min-height:44px; border:1px solid var(--site-border); border-radius:.35rem; padding:.35rem .65rem; background:var(--site-background); color:var(--site-text); font:inherit; } button { cursor:pointer; font-weight:650; } button:hover { border-color:var(--site-accent); } button:disabled { opacity:.55; cursor:wait; } .filters { display:grid; grid-template-columns:2fr 1fr 1fr; gap:.75rem; margin:1.15rem 0; } label { display:grid; gap:.3rem; color:var(--site-text-muted); font-size:.83rem; font-weight:700; } .table-wrap { overflow-x:auto; } table { width:100%; border-collapse:collapse; min-width:650px; } th,td { padding:.75rem .5rem; border-top:1px solid color-mix(in srgb,var(--site-border) 60%,transparent); text-align:left; vertical-align:middle; font-size:.9rem; } th { color:var(--site-text-muted); font-size:.78rem; } .text-button { display:block; min-height:auto; padding:0; border:0; background:transparent; color:var(--site-link); text-align:left; } small { display:block; margin-top:.25rem; color:var(--site-text-muted); } .badge { display:inline-block; padding:.2rem .45rem; border-radius:99px; background:#fef3c7; color:#92400e; font-size:.76rem; font-weight:700; } .badge.published { background:#dcfce7; color:#166534; } .danger { color:#b91c1c; } .empty { padding:1.5rem 0; color:var(--site-text-muted); } .sr-only { position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0,0,0,0); } button:focus-visible,input:focus-visible,select:focus-visible { outline:3px solid var(--site-accent); outline-offset:2px; } @media(max-width:700px){.filters{grid-template-columns:1fr}.new-actions{width:100%}.new-actions button{flex:1 1 7rem;}}
</style>
