<script lang="ts">
  import { onMount } from 'svelte';
  import type { CmsClient } from '../../services/cms/client';
  import type { CmsMedia } from '../../features/cms/types';
  export let client: CmsClient;
  export let onInsert: (markdown: string, media: CmsMedia) => void = () => {};
  export let insertMode = false;
  let items: CmsMedia[] = []; let loading = true; let uploading = false; let busy = ''; let error = ''; let message = ''; let input: HTMLInputElement;
  async function refresh() { loading = true; error = ''; try { items = await client.media(); } catch (cause) { error = cause instanceof Error ? cause.message : '图片库读取失败'; } finally { loading = false; } }
  async function upload(event: Event) { const file = (event.currentTarget as HTMLInputElement).files?.[0]; if (!file) return; uploading = true; error = ''; message = ''; try { const item = await client.upload(file); items = [item, ...items]; message = '图片已上传到私有存储。'; } catch (cause) { error = cause instanceof Error ? cause.message : '上传失败，请重试'; } finally { uploading = false; if (input) input.value = ''; } }
  async function remove(media: CmsMedia) { if (!confirm(`确定删除“${media.name}”吗？已发布引用的图片不会被删除。`)) return; busy = media.id; error = ''; try { await client.deleteMedia(media); items = items.filter((item) => item.id !== media.id); message = '图片已删除。'; } catch (cause) { error = cause instanceof Error ? cause.message : '删除失败'; } finally { busy = ''; } }
  function useMedia(media: CmsMedia) { const value = `![${media.name}](/media/${media.id})`; if (insertMode) { onInsert(value, media); message = '图片已插入当前工作副本，记得保存。'; return; } navigator.clipboard?.writeText(value).then(() => message = 'Markdown 已复制，可粘贴到正文。').catch(() => message = '无法自动复制，请在编辑器的图片工具中插入该图片。'); }
  onMount(refresh);
</script>

<section class="panel" aria-labelledby="cms-media-title"><div class="heading"><div><p class="eyebrow">私有媒体库</p><h2 id="cms-media-title">图片</h2><p>预览链接仅用于当前后台展示，不会写入文章正文。</p></div><button type="button" on:click={refresh} disabled={loading}>刷新</button></div><div class="upload"><label>上传图片（PNG、JPEG、WebP 或 GIF，不超过 10 MB）<input bind:this={input} type="file" accept="image/png,image/jpeg,image/webp,image/gif" on:change={upload} disabled={uploading} /></label><span>{uploading ? '上传中…' : insertMode ? '上传后可直接插入当前工作副本。' : '上传后可复制 /media/图片ID Markdown。'}</span></div>{#if error}<p role="alert" class="notice error">{error}</p>{/if}{#if message}<p role="status" class="notice success">{message}</p>{/if}{#if loading}<p class="empty">正在读取图片库…</p>{:else if items.length === 0}<p class="empty">尚未上传图片。</p>{:else}<ul class="media-grid">{#each items as media}<li><div class="image-box">{#if media.previewUrl}<img src={media.previewUrl} alt={media.name} />{:else}<span>无可用预览</span>{/if}</div><strong title={media.name}>{media.name}</strong><small>{media.mime} · {(media.size / 1024).toFixed(0)} KB</small><div class="actions"><button type="button" on:click={() => useMedia(media)}>{insertMode ? '插入当前正文' : '复制 Markdown'}</button><button type="button" class="danger" disabled={busy === media.id} on:click={() => remove(media)}>{busy === media.id ? '处理中…' : '删除'}</button></div></li>{/each}</ul>{/if}</section>

<style>
  .panel { padding:clamp(1rem,3vw,1.5rem); border:1px solid var(--site-border); border-radius:.7rem; background:var(--site-surface); } .heading { display:flex; flex-wrap:wrap; justify-content:space-between; align-items:start; gap:1rem; } .eyebrow { margin:0; color:var(--site-link); font-size:.8rem; font-weight:750; } h2 { margin:.15rem 0; font-size:1.45rem; } .heading p:not(.eyebrow) { margin:.35rem 0 0; color:var(--site-text-muted); font-size:.9rem; } button,input { min-height:44px; border:1px solid var(--site-border); border-radius:.35rem; padding:.4rem .7rem; background:var(--site-background); color:var(--site-text); font:inherit; } button { cursor:pointer; font-weight:650; } button:disabled { opacity:.55; cursor:wait; } .upload { display:flex; flex-wrap:wrap; align-items:end; gap:.75rem; margin:1rem 0; padding:.85rem; background:color-mix(in srgb,var(--site-tint) 40%,transparent); border-radius:.5rem; } .upload label { display:grid; gap:.35rem; font-size:.85rem; font-weight:700; } .upload input { padding:.25rem; max-width:100%; } .upload span { color:var(--site-text-muted); font-size:.85rem; } .notice { margin:.75rem 0; padding:.6rem .75rem; border-left:4px solid currentColor; } .error { color:#b91c1c; background:#fef2f2; } .success { color:#166534; background:#f0fdf4; } .empty { padding:1.25rem 0; color:var(--site-text-muted); } .media-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(180px,1fr)); gap:1rem; padding:0; list-style:none; } li { min-width:0; padding:.65rem; border:1px solid var(--site-border); border-radius:.45rem; } .image-box { display:grid; width:100%; aspect-ratio:4/3; place-items:center; overflow:hidden; background:var(--site-background); color:var(--site-text-muted); } img { width:100%; height:100%; object-fit:cover; } strong,small { display:block; overflow:hidden; margin-top:.5rem; text-overflow:ellipsis; white-space:nowrap; } small { margin-top:.15rem; color:var(--site-text-muted); font-size:.76rem; } .actions { display:grid; gap:.4rem; margin-top:.65rem; } .actions button { min-height:38px; font-size:.82rem; } .danger { color:#b91c1c; } button:focus-visible,input:focus-visible { outline:3px solid var(--site-accent); outline-offset:2px; }
</style>
