<script lang="ts">
  import { onMount } from 'svelte';
  import type { CmsClient } from '../../services/cms/client';
  import type { CmsProfile, CmsRole } from '../../features/cms/types';
  export let client: CmsClient;
  export let profile: CmsProfile;
  let members: CmsProfile[] = []; let loading = true; let busy = ''; let error = ''; let message = '';
  const isOwner = () => profile.role === 'owner';
  function allowedRoles(member: CmsProfile): CmsRole[] { if (member.role === 'owner') return ['owner']; return isOwner() ? ['admin', 'editor', 'member'] : ['editor', 'member']; }
  async function load() { loading = true; error = ''; try { members = await client.members(); } catch (cause) { error = cause instanceof Error ? cause.message : '成员列表读取失败'; } finally { loading = false; } }
  async function update(member: CmsProfile, role: CmsRole, active: boolean) { if (member.role === 'owner' || member.user_id === profile.user_id && profile.role !== 'owner') return; busy = member.user_id; error = ''; message = ''; try { const updated = await client.setMember(member.user_id, role, active); members = members.map((item) => item.user_id === updated.user_id ? updated : item); message = `已更新 @${updated.login} 的权限。`; } catch (cause) { error = cause instanceof Error ? cause.message : '成员更新失败'; } finally { busy = ''; } }
  onMount(load);
</script>

<section class="panel" aria-labelledby="cms-members-title"><div class="heading"><div><p class="eyebrow">成员与权限</p><h2 id="cms-members-title">成员管理</h2><p>GitHub 首次登录只创建普通成员账户；站长决定编辑和管理权限。</p></div><button type="button" on:click={load} disabled={loading || !!busy}>刷新</button></div>{#if error}<p role="alert" class="notice error">{error}</p>{/if}{#if message}<p role="status" class="notice success">{message}</p>{/if}{#if loading}<p class="empty">正在读取成员…</p>{:else}<div class="table-wrap"><table><thead><tr><th>账户</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{#each members as member}<tr><td><strong>{member.display_name || member.login}</strong><small>@{member.login}{member.user_id === profile.user_id ? ' · 当前账户' : ''}</small></td><td>{#if member.role === 'owner'}<span class="owner">owner</span>{:else}<select value={member.role} disabled={busy === member.user_id || (!isOwner() && member.role === 'admin')} on:change={(event) => update(member, (event.currentTarget as HTMLSelectElement).value as CmsRole, member.active)}>{#each allowedRoles(member) as role}<option value={role}>{role}</option>{/each}</select>{/if}</td><td>{#if member.role === 'owner'}<span>受保护</span>{:else}<label class="toggle"><input type="checkbox" checked={member.active} disabled={busy === member.user_id || (!isOwner() && member.role === 'admin')} on:change={(event) => update(member, member.role, (event.currentTarget as HTMLInputElement).checked)} />{member.active ? '启用' : '已停用'}</label>{/if}</td><td>{#if member.role === 'owner'}<span class="muted">owner 不可降权或停用</span>{:else if !isOwner() && member.role === 'admin'}<span class="muted">仅 owner 可管理 admin</span>{:else}<span>{busy === member.user_id ? '正在保存…' : '变更会立即生效'}</span>{/if}</td></tr>{/each}</tbody></table></div>{/if}</section>

<style>
  .panel { padding:clamp(1rem,3vw,1.5rem); border:1px solid var(--site-border); border-radius:.7rem; background:var(--site-surface); } .heading { display:flex; flex-wrap:wrap; justify-content:space-between; align-items:start; gap:1rem; } .eyebrow { margin:0; color:var(--site-link); font-size:.8rem; font-weight:750; } h2 { margin:.15rem 0; font-size:1.45rem; } .heading p:not(.eyebrow),small,.muted { color:var(--site-text-muted); font-size:.84rem; } button,select { min-height:44px; border:1px solid var(--site-border); border-radius:.35rem; padding:.4rem .7rem; background:var(--site-background); color:var(--site-text); font:inherit; } button { cursor:pointer; font-weight:650; } button:disabled,select:disabled { opacity:.55; cursor:wait; } .table-wrap { overflow-x:auto; margin-top:1rem; } table { width:100%; min-width:620px; border-collapse:collapse; } th,td { padding:.75rem .5rem; border-top:1px solid color-mix(in srgb,var(--site-border) 60%,transparent); text-align:left; vertical-align:middle; font-size:.9rem; } th { color:var(--site-text-muted); font-size:.78rem; } strong,small { display:block; } .owner { color:var(--site-link); font-weight:750; } .toggle { display:flex; align-items:center; gap:.4rem; } .toggle input { width:1.15rem; height:1.15rem; } .notice { padding:.6rem .75rem; border-left:4px solid currentColor; } .error { color:#b91c1c; background:#fef2f2; } .success { color:#166534; background:#f0fdf4; } .empty { color:var(--site-text-muted); } button:focus-visible,select:focus-visible,input:focus-visible { outline:3px solid var(--site-accent); outline-offset:2px; }
</style>
